CREATE TABLE IF NOT EXISTS teams (
    teamID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    teamName VARCHAR(255) NOT NULL UNIQUE,
    leaderID INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
    userID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    gradYear INT NOT NULL,
    participating BOOLEAN NOT NULL DEFAULT FALSE,
    teamID INT DEFAULT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    hasEated BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT userTeam
        FOREIGN KEY (teamID)
        REFERENCES teams (teamID)
);

ALTER TABLE teams
ADD CONSTRAINT teamLeader
FOREIGN KEY (leaderID)
REFERENCES users (userID);
